# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 794b1a48b9c756eb0a9636618de19bf909f9d85d2e4d34c633c8a596798d6a8491a2210f08644a80cf913e3ad6c5d1f683dfc5bd573c71e0d452b18d2e4f98ef

test:
  secret_key_base: e8a79f03117c144d12c71d3c4e239ff2b504c18f296c74587be339c449747256e7ffb1ca87718cfe7519f593c44ac171b14b1ddb76320766aaa8683225921617

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
